const danhSachSanPham = [
  {
        id: 1,
        tenSanPham: "Short nam 6inch Pickleball Smash Shot",
        danhMuc: "Pickleball",
        gia: 250000,
        hinhAnh1: "./images/Pickleball/nam-1.avif",
        hinhAnh2: "./images/Pickleball/nam.avif",
        moTa: "Chinh phục mọi trận đấu với Quần Short nam 6inch Pickleball Smash Shot, một thiết kế không thể thiếu trong bộ sưu tập quần thể thao chuyên dụng của bạn. Là một item nổi bật trong dòng sản phẩm quần nam, chiếc quần này được dệt từ sự kết hợp của 90% sợi Nylon siêu nhẹ và 10% Spandex co giãn vượt trội. Công nghệ dệt Punching độc đáo được ứng dụng ở phần đai lưng, tạo nên các lỗ thoáng khí chiến lược giúp giảm đáng kể trọng lượng và tăng cường thoát ẩm. Cảm giác nhẹ bẫng, linh hoạt và khô thoáng mà sản phẩm mang lại sẽ giúp bạn tự tin làm chủ mọi pha bóng tốc độ cao, hoàn thiện phong cách quần áo thể thao năng động của bạn.Phom Regular Fit thông minh, tiện ích vượt trội",
    },
    {
        id: 2,
        tenSanPham: "Áo tanktop Pickleball Driveshot Essentials",
        danhMuc: "Pickleball",
        gia: 223000,
        hinhAnh1: "./images/Pickleball/ao-tank-top-nu-pkb-exdry-classics-6_2-navy.jpg",
        hinhAnh2: "./images/Pickleball/ao-tank-top-nu-pkb-exdry-classics-5_2-navy.jpg",
        moTa: "hàng cho gái xinh",
    },
    {
        id: 3,
        tenSanPham: "Váy thun knit Aline Pickleball Essentials",
        danhMuc: "Pickleball",
        gia: 319000,
        hinhAnh1: "./images/Pickleball/vay-thun-knit-aline-pickleball-essentials-2-trang.avif",
        hinhAnh2: "./images/Pickleball/vay-thun-knit-aline-pickleball-essentials-1-trang.avif",
        moTa: "#",
    },
    {
        id: 4,
        tenSanPham: "Áo polo nữ Pickleball Exdry Essentials",
        danhMuc: "Pickleball",
        gia: 399000,
        hinhAnh1: "./images/Pickleball/ao-polo-nu-pkb-exdry-essentials-17-trang_61.avif",
        hinhAnh2: "./images/Pickleball/ao-polo-nu-pkb-exdry-essentials-16-trang_29.avif",
        moTa: "#",
    },
    {
        id: 5,
        tenSanPham: "Áo thun nam Pickleball Essentials siêu mát",
        danhMuc: "Pickleball",
        gia: 250000,
        hinhAnh1: "./images/Pickleball/ao-thun-nam-pickleball-dinkshot-4-xam_49.avif",
        hinhAnh2: "./images/Pickleball/ao-thun-nam-pickleball-dinkshot-3-xam_3.avif",
        moTa: "#",
    },
    {
        id: 6,
        tenSanPham: "Tất Pickleball Nam Cổ Trung Court Black",
        danhMuc: "Pickleball",
        gia: 250000,
        hinhAnh1: "./images/Pickleball/tat-the-thao-co-trung-nam-pkb-court-black-28-den-phoi-trang_64.avif",
        hinhAnh2: "./images/Pickleball/tat-the-thao-co-trung-nam-pkb-court-black-3-den-phoi-trang_56.avif",
        moTa: "#",
    },

    

    // QUẦN LÓT
    {
        id: 20,
        tenSanPham: "Combo 3 Quần Lót Nam Trunk AirMax Mesh",
        danhMuc: "QuanLot",
        gia: 237000,
        hinhAnh1: "./images/QuanLot/quan-lot-trunk-airmax-mesh-_20-navy-xanh.avif",
        hinhAnh2: "./images/QuanLot/quan-lot-trunk-airmax-mesh-_9-navy-xanh_(4).avif",
        moTa: "Combo 3 Quần Lót Nam Trunk AirMax Mesh - Thoáng Khí Tối Ưu, Co Giãn Linh Hoạt Combo 3 Quần Lót Nam Trunk AirMax Mesh mang đến sự thoải mái vượt trội với chất liệu vải lưới thoáng khí, giúp giải phóng nhiệt và giữ cho cơ thể luôn khô ráo. Với thành phần 90% Polyester và 10% Spandex, sản phẩm có khả năng thấm hút mồ hôi tốt và co giãn linh hoạt, ôm sát cơ thể mà không gây khó chịu. Công nghệ Ex-Dry đảm bảo quần nhanh khô, lý tưởng cho các hoạt động thể thao hoặc mặc hàng ngày.",
    },
    {
        id: 21,
        tenSanPham: "Combo 3 Quần Lót Nam Trunk Lenzing Modal",
        danhMuc: "QuanLot",
        gia: 250000,
        hinhAnh1: "./images/QuanLot/Den_1_(1).avif",
        hinhAnh2: "./images/QuanLot/combo1.017_(1).jpg",
        moTa: "Nâng niu cơ thể bạn với sự mềm mại và thoáng mát từ Combo 3 Quần Lót Nam Trunk, một trong những sản phẩm quần lót nam cao cấp và thân thiện nhất, sự lựa chọn hoàn hảo cho tủ quần áo thu đông của bạn.. Sản phẩm được dệt từ sợi vải Modal cao cấp của Lenzing AG (Úc), có nguồn gốc hoàn toàn tự nhiên từ gỗ sồi. Chất liệu này nổi tiếng với độ mềm mại gấp đôi so với cotton thông thường, mang đến cảm giác mát lạnh ngay khi chạm vào da. Khả năng thấm hút mồ hôi vượt trội và cấu trúc sợi thoáng khí giúp bạn luôn cảm thấy khô thoáng, dễ chịu suốt cả ngày. Đặc biệt, vải còn có tính năng kháng khuẩn tự nhiên, chống nhăn và chống xù lông hiệu quả, đảm bảo sự thoải mái và vẻ ngoài chỉn chu sau nhiều lần giặt. ",
    },
    {
        id: 22,
        tenSanPham: "Combo 3 Quần Lót Nam Trunk Bamboo",
        danhMuc: "QuanLot",
        gia: 239000,
        hinhAnh1: "./images/QuanLot/fix-1.avif", 
        hinhAnh2: "./images/QuanLot/combo-3-quan-lot-trunk-bamboo-2-den.avif",
        moTa: "Combo 3 Quần Lót Nam Trunk Bamboo Kháng Khuẩn là sự lựa chọn yêu thích của hơn 10.000 khách hàng tại Coolmate, mang đến sự mềm mịn, thoáng khí và cảm giác mặc cực kỳ dễ chịu. Sản phẩm được làm từ 95% sợi Bamboo (vải tre) tự nhiên kết hợp 5% vải Spandex. Vải Bamboo sở hữu khả năng kháng khuẩn tự nhiên, khử mùi hôi và thấm hút mồ hôi tốt hơn vải cotton gấp đôi, giúp bạn luôn khô ráo và tự tin. Cùng với công nghệ may Flat Out Seams, chiếc quần lót này mang lại sự co giãn, êm ái nhẹ nhàng, không gây hằn hay khó chịu.",
    },
    {
        id: 23,
        tenSanPham: "Combo 3 Quần lót nam Brief Lenzing Modal",
        danhMuc: "QuanLot",
        gia: 268000,
        hinhAnh1: "./images/QuanLot/combo-3-quan-quan-lot-nam-brief-lenzing-modal-mix-2.avif",
        hinhAnh2: "./images/QuanLot/combo-3-quan-quan-lot-nam-brief-lenzing-modal-mix-1.avif",
        moTa: "Combo 3 Quần lót nam Brief Lenzing Modal mang đến trải nghiệm mặc tuyệt vời với sự mềm mại vượt trội và khả năng thoáng khí tự nhiên. Sản phẩm được làm từ 91% Lenzing Modal và 9% Spandex, kết hợp hai chất liệu mang lại hiệu suất cao. Lenzing Modal nổi tiếng với bề mặt siêu mềm mịn, mang lại cảm giác êm ái trên da, đồng thời sở hữu khả năng hút ẩm và thoáng khí vượt trội, giúp bạn luôn cảm thấy khô ráo và dễ chịu. Thêm vào đó, Spandex giúp tăng cường độ co giãn, mang lại sự thoải mái khi vận động và đảm bảo độ bền, chống bai nhão, xù lông. Với những ưu điểm này, chiếc quần lót không chỉ thân thiện với môi trường mà còn là lựa chọn hoàn hảo cho sức khỏe vùng nhạy cảm của bạn.",
    },
    {
        id: 24,
        tenSanPham: "Combo 3 Quần Lót Nam Trunk Bamboo Fortune",
        danhMuc: "QuanLot",
        gia: 289000,
        hinhAnh1: "./images/QuanLot/333.avif",
        hinhAnh2: "./images/QuanLot/222.avif",
        moTa: "Đây là giải pháp toàn diện cho những ai đang tìm kiếm một bộ sưu tập quần lót nam chất lượng, đảm bảo sự thoải mái và khô thoáng cho cả tuần dài. Trái tim của sản phẩm nằm ở chất liệu vải cao cấp với 95% là sợi vải Bamboo tự nhiên, nổi tiếng với đặc tính kháng khuẩn và hạn chế mùi vượt trội. 5% vải Spandex còn lại giúp tăng cường độ co giãn, đảm bảo quần luôn ôm vừa vặn mà không gây gò bó. Khi mặc lên người chiếc quần lót nam Boxer Trunk này, bạn sẽ cảm nhận ngay lập tức sự mềm mại, mát lạnh mà sợi tre mang lại. Chất liệu này có khả năng thấm hút mồ hôi hiệu quả và khô nhanh, giúp vùng nhạy cảm luôn thoáng khí, mang lại cảm giác nhẹ tênh, dễ chịu suốt 24 giờ.",
    },
    {
        id: 25,
        tenSanPham: "Combo 3 Quần Lót Nam Trunk Excool",
        danhMuc: "QuanLot",
        gia: 263000,
        hinhAnh1: "./images/QuanLot/excool-1.jpg",
        hinhAnh2: "./images/QuanLot/excool.avif",
        moTa: "Combo 3 Quần Lót Nam Trunk Excool Microfiber Seamless là lựa chọn tối ưu, mang đến sự thoải mái, thoáng mát và khả năng kháng khuẩn vượt trội cho phái mạnh. Sản phẩm được ưa chuộng bởi hơn 10.000 khách hàng nhờ chất liệu mềm mịn, co giãn và công nghệ Seamless độc đáo. Chiếc quần lót này hội tụ tinh hoa thiết kế của Coolmate, với sự thoải mái và tiện lợi đặt lên hàng đầu. Với thành phần chính gồm 86% Microfiber siêu mịn, mát và 14% vải Spandex co giãn, bền bỉ, chiếc quần lót nam này không chỉ mang lại cảm giác dễ chịu mà còn sở hữu nhiều tính năng nổi bật.",
    },
    
    // CHẠY BỘ
    
    {
        id: 41,
        tenSanPham: "Quần shorts nữ chạy bộ 2 lớp Pace shorts 3.5IN",
        danhMuc: "ChayBo",
        gia: 379000,
        hinhAnh2: "./images/run/3.webp",
        hinhAnh1: "./images/run/4.jpg",
        moTa: "Quần shorts nữ chạy bộ 2 lớp Pace Shorts 3.5IN được thiết kế chuyên biệt cho các vận động viên và người yêu thích chạy bộ. Với thiết kế 2 lớp thông minh, lớp ngoài giúp tăng tính thẩm mỹ và kín đáo, trong khi lớp lót ôm sát bên trong giúp chống ma sát và bảo vệ tối đa. Chất liệu vải nhẹ, thoát ẩm nhanh giúp bạn luôn khô thoáng trong suốt buổi tập.",
    },
    {
        id: 42,
        tenSanPham: "Tshirt thể thao nữ Quick Dry Tight",
        danhMuc: "ChayBo",
        gia: 239000,
        hinhAnh2: "./images/run/5.webp",
        hinhAnh1: "./images/run/6.webp",
        moTa: "Áo thun thể thao nữ Quick Dry Tight sở hữu công nghệ làm mát tiên tiến, giúp cơ thể luôn khô ráo ngay cả trong những bài tập cường độ cao. Form dáng ôm vừa phải, chất vải co giãn 4 chiều mang lại sự linh hoạt tuyệt đối trong từng sải bước. Sản phẩm không chỉ hỗ trợ hiệu suất tập luyện mà còn mang phong cách năng động, hiện đại.",
    },
    {
        id: 43,
        tenSanPham: "Tshirt chạy bộ nữ Graphic Sky",
        danhMuc: "ChayBo",
        gia: 239000,
        hinhAnh2: "./images/run/7.avif",
        hinhAnh1: "./images/run/8.webp",
        moTa: "Tshirt chạy bộ nữ Graphic Sky kết hợp giữa hiệu năng vượt trội và thiết kế thời thượng với họa tiết bắt mắt. Sử dụng chất liệu vải sợi tổng hợp cao cấp có khả năng thấm hút mồ hôi cực nhanh, chiếc áo này là người bạn đồng hành lý tưởng cho những buổi chạy bộ buổi sáng hoặc tham gia các sự kiện marathon cùng bạn bè.",
    },
    {
        id: 44,
        tenSanPham: "Tshirt chạy bộ nam Gradient",
        danhMuc: "ChayBo",
        gia: 239000,
        hinhAnh2: "./images/run/9.avif",
        hinhAnh1: "./images/run/10.webp",
        moTa: "Tshirt chạy bộ nam Gradient nổi bật với thiết kế phối màu chuyển sắc độc đáo. Sản phẩm được nghiên cứu kỹ lưỡng để tối ưu hóa sự thông thoáng, giúp luồng khí lưu thông tốt hơn trong quá trình chạy. Vải nhẹ, mềm mại với làn da, không gây hầm bí, giúp nam giới tự tin chinh phục mọi cung đường.",
    },
    {
        id: 45,
        tenSanPham: "Áo thun chạy bộ nam Airflow Exdry Gradient",
        danhMuc: "ChayBo",
        gia: 299000,
        hinhAnh2: "./images/run/11.webp",
        hinhAnh1: "./images/run/12.webp",
        moTa: "Áo thun nam Airflow Exdry Gradient tích hợp công nghệ làm mát đột phá, giúp giảm nhiệt cơ thể nhanh chóng khi vận động. Chất liệu vải đặc biệt với cấu trúc dệt thông minh giúp đẩy mồ hôi ra ngoài bề mặt vải, đảm bảo bạn luôn thoải mái, không bết dính. Thiết kế nam tính, mạnh mẽ phù hợp với cả chạy bộ và tập gym.",
    },
    {
        id: 46,
        tenSanPham: "Tshirt chạy bộ nữ Exdry AeroDot Gradient",
        danhMuc: "ChayBo",
        gia: 239000,
        hinhAnh2: "./images/run/1.avif",
        hinhAnh1: "./images/run/2.jpg",
        moTa: "Tshirt chạy bộ nữ Exdry AeroDot Gradient với công nghệ lỗ thoát khí li ti (AeroDot) giúp tăng cường khả năng thoáng khí gấp nhiều lần so với vải thông thường. Đây là sự lựa chọn hoàn hảo cho những ngày hè nắng nóng. Thiết kế thời trang, trẻ trung cùng khả năng khử mùi tốt giúp bạn luôn tự tin sau mỗi buổi tập luyện.",
    },
    
];